### PR TITLE
Dez

### PR DESCRIPTION
**Pull request by giamic**
Introduce a new converter from Rn directly to Dez. Add a couple of tests

NB: This breaks the tonality because I don't remember how to read all the different tonalities from a score in music21. Let's talk about it.

### CODE REVIEW

**Comment by MarkGotham** [comment]
Thanks @giamic ! 

When music21 parses rntxt ... 
- it stores `roman.RomanNumeral` objects on a `stream.Part` ...
- which can be extracted with `.recurse().getElementsByClass(roman.RomanNumeral)` ...
- and on which key and chord are attributes.

So the way to get changes to either is if `this_object.attribute != prev_object.attribute`. (This can be by keeping a record go the previous state, or there's actually music21 `.previous()` functionality for this now.) Debatable whether to do this for chord as it's feasible that an exact repeat would be wanted, but definitely for key changes.

Obviously the key signatures on the part are not it at all.

Happy to chat.

**Comment by MarkGotham** [comment]
i.e. / e.g.

```
from music21 import corpus
analysis = corpus.parse("bach/choraleAnalyses/riemenschneider005.rntxt")
rns = analysis.recurse().getElementsByClass(roman.RomanNumeral)
previous_key = "FAKE!"
for rn in rns:
    if rn.key != previous_key:
        previous_key = rn.key
        print(rn.measureNumber, previous_key)
```

**Comment by giamic** [comment]
Nice! Thanks for letting me know. Then we should already have everything we need. I will update this PR maybe this Wednesday with the full solution!

**Comment by giamic** [comment]
I have implemented the change you suggested and it seems to work. I have updated the reference dezrann file to the new one, which has the following differences:
- The tonality labels are no longer all at the beginning of the dezrann file. This change can be easily reverted with a few more lines of code, but I thought it'd be preferable to keep the code as clean and simple as possible
- Some of the chord figures have changed because they no longer have to pass through the tab conversion. Please check that all changes make sense because I think that the previous conversion might have been buggy
- The key figures have changed. Now it's no longer `Db` but `D- major`, following music21's convention

Let me know if it all looks good to you!

**Comment by MarkGotham** [comment]
Hi @giamic, thanks for this! Some good progress here. I've added a few small/obvious edits and added a quick, direct rn to dez conversion for discussion (no score required).

As I see it, here is the current status:
1. remove unnecessary intermediate `tab` state = DONE by you, thanks 👍 
2. remove unnecessary score import = under discussion, sketched by me just now
3. remove unnecessary wrangling with measure offsets = under discussion, sketched by me just now

Wrt 2./3. the new `rn2dez` shows how we could get the offsets directly from the analysis, and even directly from the RNs without recourse to the measure (which dez doesn't use anyway). I argue that we _should_ do this because it helps:
- save on processing
  - score parsing is probably the heaviest part of this process and 
  - the `.currentHierarchyOffset` iterator on one class is especially fast/light).
- avoid any discrepancies there might be
  - between score and analysis (get all data from one place) and 
  - arising from counts/addition on offsets via measures.

What do you think? It could stand alone (apart from the Tab logic here) or else be integrated?

**Pull request merged**
