### PR TITLE
Haydn analysis corrections

### PR DESCRIPTION
**Pull request by malcolmsailor**
Some corrections to the Haydn analyses.

### CODE REVIEW

**Comment by MarkGotham** [comment]
Thanks!
These seem to be errors in the analysis at source right? 
@napulen do you agree? Would you like to fix at source and re-convert?

**Comment by malcolmsailor** [comment]
> These seem to be errors in the analysis at source right?

I believe so, yes

**Comment by napulen** [comment]
Corroborated a few of these, definitely errors on my end! Thanks, @malcolmsailor!

**Comment by napulen** [comment]
Given the always problematic treatment of `/vi` `/bvii` `/#vi`, etc. in translations. I suggest going with these changes as they are. I spotted wrong inversions already in other annotations around Malcolm's corrections. I'd prefer to re-analyze the set (I think the output by AugmentedNet will help to spot more errors) and follow a more strict convention for inversions/tonicizations.

**Comment by MarkGotham** [comment]
Ok, thanks @napulen .

**Pull request merged**
